spring:
    profiles:
        active:
        - dev
---
server: 
    port: 8001
spring:
    profiles: dev #
    application:
        name: microservicecloud-config-provider
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    #    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    #    url: jdbc:mysql://localhost:3306/microservicecloud              # 数据库名称
        driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
        url: jdbc:mysql://localhost:3306/springcloud_test_season1_db01?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false              # 数据库名称
        username: root
        password: root
        dbcp2:
          min-idle: 5                                           # 数据库连接池的最小维持连接数
          initial-size: 5                                       # 初始化连接数
          max-total: 5                                          # 最大连接数
          max-wait-millis: 200                                  # 等待连接获取的最大超时时间
          
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.example.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  
eureka: 
    instance:
        hostname: microservicecloud-config-provider-8001
        prefer-ip-address: true     #访问路径可以显示IP地址
    client: 
        service-url: 
            defaultZone: http://eureka7001.com:7001/eureka/
            
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
    port: 8002
spring:
    profiles: test #
    application:
        name: microservicecloud-config-provider
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    #    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    #    url: jdbc:mysql://localhost:3306/microservicecloud              # 数据库名称
        driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
        url: jdbc:mysql://localhost:3306/springcloud_test_season1_db02?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false              # 数据库名称
        username: root
        password: root
        dbcp2:
          min-idle: 5                                           # 数据库连接池的最小维持连接数
          initial-size: 5                                       # 初始化连接数
          max-total: 5                                          # 最大连接数
          max-wait-millis: 200                                  # 等待连接获取的最大超时时间
          
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.example.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  
eureka: 
    instance:
        hostname: microservicecloud-config-provider-8002
        prefer-ip-address: true     #访问路径可以显示IP地址
    client: 
        service-url: 
            defaultZone: http://eureka7002.com:7002/eureka/
            
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
